# Generated by Django 4.1.2 on 2022-11-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_enadop_persona_rename_animal_adop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adop',
            new_name='Animal',
        ),
        migrations.DeleteModel(
            name='enadop',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
