# Generated by Django 4.1.2 on 2022-12-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_gato_personas_rename_animal_perro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='tipo',
        ),
    ]
